services:
  web:
    build: .
    user: "0:0"
    command: bin/rails server -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    environment:
      RAILS_ENV: development

volumes:
  bundle:
